name: Rust

on:
    push:
        branches:
        - main

    pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        rust: [stable, beta, nightly, 1.61.0, 1.57.0]

    steps:
    - uses: actions/checkout@v2
    - name: enable-rust-1_61
      if: matrix.rust == '1.61.0'
      run: echo "rustv=rust_1_61" >> $GITHUB_ENV

    - name: enable-rust-stable
      if: matrix.rust == 'stable' || matrix.rust == 'beta' || matrix.rust == 'nightly'
      run: echo "rustv=rust_stable" >> $GITHUB_ENV

    - uses: actions/checkout@v2
    - name: ci-all-versions
      run: |
        echo "rustv = ${{env.rustv}}"
        set -ex
        rustup override set ${{ matrix.rust }}
        cargo update

        cd "${{github.workspace}}/"
        cargo test --no-default-features 
        cargo test --no-default-features --features "${{env.rustv}}"
        cargo test --no-default-features --features "alloc"
        cargo test --no-default-features --features "${{env.rustv}} alloc"

    - uses: actions/checkout@v2
    - name: ci-nighly
      if: ${{ matrix.rust == 'nightly' && runner.os == 'Linux' }}
      run: |
        set -ex
        rustup override set ${{ matrix.rust }}

        cd "${{github.workspace}}/"
        cargo build
        
        cargo test --no-default-features --features "rust_stable nightly_mut_refs"
        cargo test --no-default-features --features "rust_stable alloc nightly_mut_refs"
        cargo test --no-default-features --features "rust_stable __ui_tests alloc nightly_mut_refs"

        MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
        echo "Installing latest nightly with Miri"
        echo "$MIRI_NIGHTLY"
        rustup set profile minimal
        rustup default "$MIRI_NIGHTLY"
        rustup override set "$MIRI_NIGHTLY"
        rustup component add miri
        cargo miri setup

        cargo clean 

        env RUST_BACKTRACE=0 cargo miri test --no-default-features \
            --features "${{env.rustv}} alloc nightly_mut_refs"
